version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: watchlog-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: watchlog
      POSTGRES_USER: watchlog_user
      POSTGRES_PASSWORD: watchlog_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - watchlog-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U watchlog_user -d watchlog"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watchlog-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - USER=watchlog_user
      - HOST=postgres
      - DATABASE=watchlog
      - PASSWORD=watchlog_password
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - watchlog-network

volumes:
  postgres_data:

networks:
  watchlog-network:
    driver: bridge
