import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SideNavbar from "@/components/navbar/side-navbar";
import TopNavbar from "@/components/navbar/top-navbar";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WatchLog",
  description: "Generated by create WatchLog",
  icons: {
    icon: [
      {
        url: "/icon.svg",
        type: "image/svg+xml",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex h-screen overflow-hidden">
            <div className="w-64 pr-4 pl-7 border-r-2 overflow-y-auto fixed h-full">
              <SideNavbar />
            </div>
            <div className="flex-1 ml-64">
              <div className="h-screen overflow-y-auto">
                <div className="px-6 bg-background">
                  <div className="max-w-7xl w-full mx-auto">
                    <TopNavbar />
                    <main className="mt-4 mb-8">{children}</main>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
