import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SideNavbar from "@/components/navbar/side-navbar";
import TopNavbar from "@/components/navbar/top-navbar";
import ReactQueryProvider from "@/utils/providers/react-query-provider";
import { initializeBackupScheduler } from "@/utils/service/files/backup/backupScheduler";

const inter = Inter({ subsets: ["latin"] });

// Yedekleme sistemini başlat
initializeBackupScheduler()
  .then(() => console.log("Yedekleme sistemi başlatıldı"))
  .catch(console.error);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <div className="flex">
            <div className="w-64 pr-4 pl-7 border-r-2 h-screen">
              {" "}
              {/* Side nav kısım */}
              <SideNavbar />
            </div>
            <div className="flex-grow px-6 bg-[#fdfdff] flex flex-col items-center h-screen">
              <div className="max-w-6xl w-full">
                <TopNavbar />
                <main className="mt-4 mb-8">{children}</main>
              </div>
            </div>
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
