import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNavbar from "@/components/navbar/side-navbar";
import TopNavbar from "@/components/navbar/top-navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="w-64 border-2 border-red-500 pr-4 pl-7"> {/* Side nav kısım */}
            <SideNavbar />
          </div>
          <div className="border-2 border-green-600 flex-grow px-6 bg-[#fdfdff]">
            <TopNavbar />
            <main className="mt-4 mb-8">            
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
